package config

import "os"

var (
	GO_ENV      = os.Getenv("HOMEDY_ENV")
	SERVER_PORT = os.Getenv("HOMEDY_PORT")
	APP_SECRET  = os.Getenv("HOMEDY_SECRET")

	DB_HOST = os.Getenv("HOMEDY_DB_HOST")
	DB_PORT = os.Getenv("HOMEDY_DB_PORT")
	DB_USER = os.Getenv("HOMEDY_DB_USER")
	DB_PASS = os.Getenv("HOMEDY_DB_PASS")
	DB_NAME = os.Getenv("HOMEDY_DB_NAME")

	REFRESH_SECRET = os.Getenv("HOMEDY_REFRESH_SECRET")
	ACCESS_SECRET  = os.Getenv("HOMEDY_ACCESS_SECRET")

	TERMINAL_USER = os.Getenv("HOMEDY_TERMINAL_USER")

	MAIL_HOST  = os.Getenv("HOMEDY_MAIL_HOST")
	MAIL_USER  = os.Getenv("HOMEDY_MAIL_USER")
	MAIL_PASS  = os.Getenv("HOMEDY_MAIL_PASS")
	MAIL_OWNER = os.Getenv("HOMEDY_MAIL_OWNER")
)

func ReloadEnv() {
	GO_ENV = os.Getenv("HOMEDY_ENV")
	SERVER_PORT = os.Getenv("HOMEDY_PORT")
	APP_SECRET = os.Getenv("HOMEDY_SECRET")

	DB_HOST = os.Getenv("HOMEDY_DB_HOST")
	DB_PORT = os.Getenv("HOMEDY_DB_PORT")
	DB_USER = os.Getenv("HOMEDY_DB_USER")
	DB_PASS = os.Getenv("HOMEDY_DB_PASS")
	DB_NAME = os.Getenv("HOMEDY_DB_NAME")

	REFRESH_SECRET = os.Getenv("HOMEDY_REFRESH_SECRET")
	ACCESS_SECRET = os.Getenv("HOMEDY_ACCESS_SECRET")

	TERMINAL_USER = os.Getenv("HOMEDY_TERMINAL_USER")

	MAIL_HOST = os.Getenv("HOMEDY_MAIL_HOST")
	MAIL_USER = os.Getenv("HOMEDY_MAIL_USER")
	MAIL_PASS = os.Getenv("HOMEDY_MAIL_PASS")
	MAIL_OWNER = os.Getenv("HOMEDY_MAIL_OWNER")
}
