package config

import "os"

var (
	GO_ENV       = os.Getenv("HOMEDY_ENV")
	SERVER_PORT  = os.Getenv("HOMEDY_PORT")
	APP_SECRET   = os.Getenv("HOMEDY_SECRET")
	APP_URL      = os.Getenv("HOMEDY_BACKEND_URL")
	FRONTEND_URL = os.Getenv("HOMEDY_FRONTEND_URL")

	DB_HOST = os.Getenv("HOMEDY_DB_HOST")
	DB_PORT = os.Getenv("HOMEDY_DB_PORT")
	DB_USER = os.Getenv("HOMEDY_DB_USER")
	DB_PASS = os.Getenv("HOMEDY_DB_PASS")
	DB_NAME = os.Getenv("HOMEDY_DB_NAME")

	REDIS_ADDR = os.Getenv("HOMEDY_REDIS_ADDR")
	REDIS_PASS = os.Getenv("HOMEDY_REDIS_PASS")

	GITHUB_OAUTH_CLIENT_ID     = os.Getenv("HOMEDY_G_O_CLIENT_ID")
	GITHUB_OAUTH_CLIENT_SECRET = os.Getenv("HOMEDY_G_O_CLIENT_SECRET")

	REFRESH_SECRET = os.Getenv("HOMEDY_REFRESH_SECRET")
	ACCESS_SECRET  = os.Getenv("HOMEDY_ACCESS_SECRET")

	TERMINAL_USER = os.Getenv("HOMEDY_TERMINAL_USER")

	MAIL_HOST  = os.Getenv("HOMEDY_MAIL_HOST")
	MAIL_USER  = os.Getenv("HOMEDY_MAIL_USER")
	MAIL_FROM  = os.Getenv("HOMEDY_MAIL_FROM")
	MAIL_PASS  = os.Getenv("HOMEDY_MAIL_PASS")
	MAIL_OWNER = os.Getenv("HOMEDY_MAIL_OWNER")

	SIGNUP_IDENTIFIER_KEY   = os.Getenv("HOMEDY_SIGNUP_IDENTIFIER_KEY")
	NOTE_CRYPTO_KEY         = os.Getenv("HOMEDY_NOTE_CRYPTO_KEY")
	GITHUB_OAUTH_CRYPTO_KEY = os.Getenv("HOMEDY_G_O_CRYPTO_KEY")
	DEPLOY_ENV_CRYPTO_KEY   = os.Getenv("HOMEDY_DEPLOY_ENV_CRYPTO_KEY")
)

func ReloadEnv() {
	GO_ENV = os.Getenv("HOMEDY_ENV")
	SERVER_PORT = os.Getenv("HOMEDY_PORT")
	APP_SECRET = os.Getenv("HOMEDY_SECRET")
	APP_URL = os.Getenv("HOMEDY_URL")
	FRONTEND_URL = os.Getenv("HOMEDY_FRONTEND_URL")

	DB_HOST = os.Getenv("HOMEDY_DB_HOST")
	DB_PORT = os.Getenv("HOMEDY_DB_PORT")
	DB_USER = os.Getenv("HOMEDY_DB_USER")
	DB_PASS = os.Getenv("HOMEDY_DB_PASS")
	DB_NAME = os.Getenv("HOMEDY_DB_NAME")

	REDIS_ADDR = os.Getenv("HOMEDY_REDIS_ADDR")
	REDIS_PASS = os.Getenv("HOMEDY_REDIS_PASS")

	GITHUB_OAUTH_CLIENT_ID = os.Getenv("HOMEDY_G_O_CLIENT_ID")
	GITHUB_OAUTH_CLIENT_SECRET = os.Getenv("HOMEDY_G_O_CLIENT_SECRET")

	REFRESH_SECRET = os.Getenv("HOMEDY_REFRESH_SECRET")
	ACCESS_SECRET = os.Getenv("HOMEDY_ACCESS_SECRET")

	TERMINAL_USER = os.Getenv("HOMEDY_TERMINAL_USER")

	MAIL_HOST = os.Getenv("HOMEDY_MAIL_HOST")
	MAIL_USER = os.Getenv("HOMEDY_MAIL_USER")
	MAIL_PASS = os.Getenv("HOMEDY_MAIL_PASS")
	MAIL_FROM = os.Getenv("HOMEDY_MAIL_FROM")
	MAIL_OWNER = os.Getenv("HOMEDY_MAIL_OWNER")

	SIGNUP_IDENTIFIER_KEY = os.Getenv("HOMEDY_SIGNUP_IDENTIFIER_KEY")
	NOTE_CRYPTO_KEY = os.Getenv("HOMEDY_NOTE_CRYPTO_KEY")
	GITHUB_OAUTH_CRYPTO_KEY = os.Getenv("HOMEDY_G_O_CRYPTO_KEY")
	DEPLOY_ENV_CRYPTO_KEY = os.Getenv("HOMEDY_DEPLOY_ENV_CRYPTO_KEY")
}
